### PR TITLE
Implement the fix for multiple input tags in cattag command

### LINKED ISSUE #219: Multiple tags in  cattag input only affects one tag
image

Example use case is here, where only the last tag input is changed

### PR DESCRIPTION
**Pull request by yooplo**
This should correctly allow the user to recategorize multiple tags in a single command

for example: cattag t/tag1 t/tag2 t/tag3 category

Closes #219

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/CategorizeTagCommand.java [hunk 1]
```diff
@@ -26,32 +27,35 @@ public class CategorizeTagCommand extends Command {
...
 
     @Override
     public CommandResult execute(Model model) throws CommandException {
         assert model != null;
-        if (!model.containsTag(targetTag)) {
-            throw new CommandException(String.format(MESSAGE_TAG_NOT_EXIST, targetTag));
-        }
-        TagCategory existingCat = model.getTagCategory(targetTag);
-        if (isDuplicateCategory(existingCat)) {
-            throw new CommandException(String.format(MESSAGE_DUPLICATE_CATEGORY, targetTag, updatedCategory));
```
Comment (chrisjohntan) [inline src/main/java/seedu/address/logic/commands/CategorizeTagCommand.java:51]: I think we still need to show an error and block the command when the category is a duplicate. This is to prevent a unchanged state from being saved to the history stack.

**Review by chrisjohntan — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/address/logic/commands/CategorizeTagCommand.java [hunk 2]
```diff
@@ -3,15 +3,17 @@
...
 import seedu.address.model.Model;
 import seedu.address.model.tag.Tag;
 import seedu.address.model.tag.TagCategory;
 
 
 /**
- * Implements command to categorize all occurrences of a tag.
- * Format: cattag t/TAG CATEGORY
+ * Implements command to categorize all occurrences of specified tags.
+ * Format: cattag t/TAG1 t/TAG2 ... t/TAGn CATEGORY
```
Comment (KrashKart) [inline src/main/java/seedu/address/logic/commands/CategorizeTagCommand.java:16]: Should we use this format for multiple tags or use t/TAG [t/MORE_TAGS] since the tags after TAG1 are optional? (t/TAG1 [t/TAG2...t/TAGn] maybe?

File: src/main/java/seedu/address/logic/commands/CategorizeTagCommand.java [hunk 3]
```diff
@@ -26,33 +28,36 @@ public class CategorizeTagCommand extends Command {
...
+                throw new CommandException(String.format(MESSAGE_DUPLICATE_CATEGORY, targetTag, updatedCategory));
+            }
+            model.setTagsCategory(targetTag, updatedCategory);
+            model.refreshCampusConnect();
         }
-        model.setTagsCategory(targetTag, updatedCategory);
-        model.refreshCampusConnect();
-        return new CommandResult(String.format(MESSAGE_CAT_TAG_SUCCESS, targetTag));
+
+        return new CommandResult(String.format(MESSAGE_CAT_TAG_SUCCESS, targetTags));
```
Comment (chrisjohntan) [inline src/main/java/seedu/address/logic/commands/CategorizeTagCommand.java:60]: Sorry, last comment. Should we make the command successful only when all the tags are valid? If not the user might not get feedback that one tag succeeded but the other did not.
Maybe we should loop through the tags and check duplicate + validity, before setting the categories and refreshing.

**Review by chrisjohntan — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/address/logic/commands/CategorizeTagCommand.java (hunk 3 above)
Comment (yooplo) [reply src/main/java/seedu/address/logic/commands/CategorizeTagCommand.java:60]: Hmm but then we would need to change the formatting of the display, add in a new message for that scenario. Would it be easier to just disallow the whole imput.

Comment (chrisjohntan) [reply src/main/java/seedu/address/logic/commands/CategorizeTagCommand.java:60]: > Would it be easier to just disallow the whole input.

Yeah thats what I mean, we should verify all the tags first before doing the model logic outside the loop.
No worries, we merge first, I will add on in another PR.

**Review by chrisjohntan — APPROVED** [review]
