### PR TITLE
Fix bug where the tag list in the GUI does not update instantly

### LINKED ISSUE #111: Fix the issue where the taglist does not refresh when a new contact is added

### PR DESCRIPTION
**Pull request by yooplo**
Fixes #111 

Bug is fixed

### CODE REVIEW

File: src/main/java/seedu/address/model/ModelManager.java [hunk 1]
```diff
@@ -99,50 +103,56 @@ public boolean hasPerson(Person person) {
...
+    //=========== Tag List Accessors =================================================
+
     /**
-     * Returns a list of tags currently defined in CampusConnect
+     * Refreshes and returns an unmodifiable view of the list of tags currently in CampusConnect
      */
-    @Override
-    public ObservableList<Tag> getListOfCurrentTags() {
-        return this.currentlyDefinedTags;
+    private void refreshTagList() {
```
Comment (CYX22222003) [inline src/main/java/seedu/address/model/ModelManager.java:149]: This method definitely solves the bug.

**Review by CYX22222003 — APPROVED** [review]
