### PR TITLE
Fix unit test cases

### LINKED ISSUE #180: Addtag command success incorrect display message
Addtag command success message displays the whole person object without the tag added
image
State after `addtag 1 t/1234` was executed (`[1234]` not shown)

Let's fix the message to:
- show the updated person with the added tag
- or show just the added tag alone

### PR DESCRIPTION
**Pull request by KrashKart**
Closes #180

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/AddTagCommandTest.java [hunk 1]
```diff
@@ -81,14 +82,16 @@ public void execute_validTagsAndIndex_tagsAdded() {
 
         // add one valid tag to person with pre-existing tag
         addTagCommand = new AddTagCommand(indexOne, oneTag);
-        expectedMessage = String.format(AddTagCommand.MESSAGE_ADD_TAG_SUCCESS, Messages.format(ALICE));
-        expectedModel.addPersonTags(ALICE, oneTag);
+        expectedModel.addPersonTags(ALICE, oneTag); // add the tag to ALICE through the expected model
+        Person newAlice = ALICE.addTag(oneTag); // add the tag to ALICE manually to get the success message
```
Comment (CYX22222003) [inline src/test/java/seedu/address/logic/commands/AddTagCommandTest.java:86]: Good to update test cases to adapt to the new changes in addTagCommand

**Review by CYX22222003 — APPROVED** [review]
LGTM
