### PR TITLE
Version campus connect refactor

### LINKED ISSUE #146: Refactor undo and redo command
1. Abstract out the `prev` and `future` stack out.
2. `undo` and `redo` should not save instance when an `CommandException` is thrown

### PR DESCRIPTION
**Pull request by CYX22222003**
Fix #146

### CODE REVIEW

File: src/main/java/seedu/address/logic/Messages.java [hunk 1]
```diff
@@ -21,6 +21,10 @@ public class Messages {
     public static final String MESSAGE_NO_TAG = "The person does not contain the tag";
     public static final String MESSAGE_TAG_NOT_FOUND = "There is no tag presented in the command!";
     public static final String MESSAGE_DELETE_TAG_SUCCESS = "Tag %1$s is deleted from student %2$s";
+
+    public static final String MESSAGE_UNDO_FAILURE = "Already at the oldest change";
+
+    public static final String MESSAGE_REDO_FAILURE = "Already at the latest change";
```
Comment (KrashKart) [inline src/main/java/seedu/address/logic/Messages.java:27]: Nice appropriate failure messages!

File: src/main/java/seedu/address/model/exceptions/RedoException.java [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+ * Exception when fail to execute redo.
+ */
+public class RedoException extends CommandException {
+    public RedoException(String message) {
+        super(message);
+    }
+
+    public RedoException(String message, Throwable cause) {
+        super(message, cause);
+    }
```
Comment (KrashKart) [inline src/main/java/seedu/address/model/exceptions/RedoException.java:15]: seems like this constructor is not used

File: src/main/java/seedu/address/model/exceptions/UndoException.java [hunk 3]
```diff
@@ -0,0 +1,16 @@
...
+ * Exception when fails to execute undo.
+ */
+public class UndoException extends CommandException {
+    public UndoException(String message) {
+        super(message);
+    }
+
+    public UndoException(String message, Throwable cause) {
+        super(message, cause);
+    }
```
Comment (KrashKart) [inline src/main/java/seedu/address/model/exceptions/UndoException.java:15]: seems like this constructor is also not used

File: src/main/java/seedu/address/model/CampusConnect.java [hunk 4]
```diff
@@ -49,36 +53,26 @@ public CampusConnect(ReadOnlyCampusConnect toBeCopied) {
...
-            prev.push(new CampusConnect(this));
-            assert out != null;
-            return out;
-        } else {
-            return new CampusConnect(this);
-        }
+    public ReadOnlyCampusConnect recoverUndoneState() throws RedoException {
+        ReadOnlyCampusConnect out = versionedCampusConnect.extractUndoneData();
+        versionedCampusConnect.saveOldData(new CampusConnect(this));
+        return out;
```
Comment (KrashKart) [inline src/main/java/seedu/address/model/CampusConnect.java:75]: Can add unit tests

File: src/main/java/seedu/address/model/VersionedCampusConnect.java [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+        }
+        return history.pop();
+    }
+
+    /**
+     * Saves history data into history stack.
+     * Data should not be null.
+     */
+    public void saveOldData(ReadOnlyCampusConnect data) {
+        assert data != null;
```
Comment (KrashKart) [inline src/main/java/seedu/address/model/VersionedCampusConnect.java:49]: can use requireNonNull instead of assert?

**Review by KrashKart — APPROVED** [review]
LGTM! Perhaps can implement a few changes and remove some bloat if required (can do later)
