### PR TITLE
Fix cattag not updating person list in the UI

### LINKED ISSUE #203: PersonsList does not update tag category in the UI

### LINKED ISSUE #204: Person tags do not change color after cattag command is executed

### LINKED ISSUE #207: Person list in UI not updating after cattag command
Possible duplicate of #204 and #203 

Issue as reported in #206 

Issues:
- Currently, list command is needed after `cattag` to update the person list in UI
- But `list` works once only, subsequent `cattag` commands do not update the person list in the UI. Code tracing confirms that the campusConnect model's `UniquePersonList` stores the consistent person and tag objects with the correct categories, but they are not being reflected in the UI person list. And in fact the `filteredPersonList` also stores the correct instances

Steps to replicate (command sequence) assuming there already exists a person with tag XX in campusConnect:
1. `cattag t/XX acads` (left half does not update, right half updates)
2. `list` (left half updates)
3. `cattag t/XX activity` (left half does not update, right half updates)
4. `list` (nothing updates!)

Strangely, the subsequent steps fix the problem:
5. `undo`
6. `redo` (now it updates XX to `ACTIVITIES`)

### PR DESCRIPTION
**Pull request by chrisjohntan**
This should:
- Force `campusConnect` to refresh with the updated tags in the displayed person list

Fixes #203, fixes #204, fixes #207

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/CategorizeTagCommand.java [hunk 1]
```diff
@@ -51,6 +51,7 @@ public CommandResult execute(Model model) throws CommandException {
             throw new CommandException(String.format(MESSAGE_DUPLICATE_CATEGORY, targetTag, updatedCategory));
         }
         model.setTagsCategory(targetTag, updatedCategory);
+        model.refreshCampusConnect();
```
Comment (yooplo) [inline src/main/java/seedu/address/logic/commands/CategorizeTagCommand.java:54]: This would most definitely refresh the PersonList whenever the command is executed.

**Review by yooplo — APPROVED** [review]
This should update the Person list in the UI.
