### PR TITLE
Fix small bug with display message.

### LINKED ISSUE #184: Cattag message description
Tidy up the `MESSAGE_USAGE` of `cattag`:
image

### PR DESCRIPTION
**Pull request by yooplo**
Close #184

Add spacing after the colon and place the different sections onto new lines.

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/CategorizeTagCommand.java [hunk 1]
```diff
@@ -18,8 +18,8 @@ public class CategorizeTagCommand extends Command {
     public static final String COMMAND_WORD = "cattag";
 
     public static final String MESSAGE_USAGE = COMMAND_WORD
-            + ":Categorizes a tag. Changes all occurrences of the specified tag to the desired category."
-            + "Parameters: " + PREFIX_TAG + "TAG (existing tag label) CATEGORY"
+            + ": Categorizes a tag. Changes all occurrences of the specified tag to the desired category.\n"
+            + "Parameters: " + PREFIX_TAG + "TAG (existing tag label) CATEGORY\n"
```
Comment (KrashKart) [inline src/main/java/seedu/address/logic/commands/CategorizeTagCommand.java:22]: Nice addition of spaces!

**Review by KrashKart — APPROVED** [review]
LGTM!
